# Dependencies
highlighter:      'rouge'

# Permalinks
permalink:        pretty

# Setup
title:            Morungos
description:      'Morungos Blog'
url:              http://morungos.github.io

author:
  name:           '@morungos'
  url:            http://morungos.github.io

paginate:         5

# Custom vars
version:          1.0.0
